### PR TITLE
Fix/python3 install

### PR DESCRIPTION
**Pull request by rokusottervanger**
## Proposed change(s)

Added catkin_install_python in CMakeLists to fix compatibility with Python3 installations

### Useful links (GitHub issues, JIRA tickets, forum threads, etc.)

[Provide any relevant links here.](http://docs.ros.org/en/noetic/api/catkin/html/howto/format2/installing_python.html)

### Types of change(s)

- [x] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other (please describe)

## Testing and Verification

Running the ROS node before this change results in errors such as `no module named yaml` because of a Python version mismatch.

Running with this change succesfully starts the ROS node.

### Test Configuration:
- ROS machine OS + version: [e.g. Ubuntu 18.04, ROS Noetic]

## Checklist
- [x] Ensured this PR is up-to-date with the `dev` branch
- [x] Created this PR to target the `dev` branch
- [x] Followed the style guidelines as described in the [Contribution Guidelines](https://github.com/Unity-Technologies/ROS-TCP-Endpoint/blob/main/CONTRIBUTING.md)
- [ ] Added tests that prove my fix is effective or that my feature works
- [x] Updated the [Changelog](https://github.com/Unity-Technologies/ROS-TCP-Endpoint/blob/dev/CHANGELOG.md) and described changes in the [Unreleased section](https://github.com/Unity-Technologies/ROS-TCP-Endpoint/blob/dev/CHANGELOG.md#unreleased)
- [x] Updated the documentation as appropriate

## Other comments

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/ROS-TCP-Endpoint?pullRequest=114) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/ROS-TCP-Endpoint?pullRequest=114) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/ROS-TCP-Endpoint?pullRequest=114) it.</sub>

**Comment by lorenz-halt** [comment]
Please merge this.
The addition is fully ROS-conform:
http://wiki.ros.org/UsingPython3/SourceCodeChanges#Changing_shebangs
https://github.com/ros/catkin/blob/0baff3a78c3ca1fcbf65493a8d656054a61a6c12/cmake/catkin_install_python.cmake#L1-L13

**Comment by ShubhamNandi** [comment]
I changed the shebang in the '**_default_server_endpoint.py_**' from '**_#!/usr/bin/env python_**' -> '**_#!/usr/bin/env python3_**' have tested it and works fine with ros **_noetic_** and **_python3_**

**Comment by rokusottervanger** [comment]
That's not a fix, it's a workaround. Handling different python versions is implemented in this CMake macro that I proposed in this PR.

**Comment by rokusottervanger** [comment]
But this was fixed in #141, so I'm closing this.

**Pull request closed without merging**
